[package]
name = "suimon_suimon_staking"
version = "0.0.1"

[dependencies]
# Sui framework is automatically added by the compiler
suimon_token = { local = "../SUIMON token" }

[addresses]
suimon_token_paid_room = "0x0"
suimon_token = "0xaae614cf7c6801a95b25d32bd3b9006d4b9f9841e9876584de37e885062d9425"
suimon_game = "0x0"